  services:
    mysql:
      image: mysql:8
      container_name: mysql-university
      environment:
        MYSQL_ROOT_PASSWORD: your_root_password
        MYSQL_DATABASE: university_db
      ports:
        - "3306:3306"
      volumes:
        - mysql_university_data:/var/lib/mysql
  volumes:
    mysql_university_data: