# Test script to verify password change functionality
import requests
import json

base_url = "http://127.0.0.1:8000"

def test_admin_password_reset():
    print("Testing Admin Password Reset...")
    
    # Test request password reset
    response = requests.post(f"{base_url}/admin/request-password-reset", 
                           json={"email": "vuquangdung71104@gmail.com"})
    
    print(f"Request Password Reset Status: {response.status_code}")
    if response.status_code == 200:
        print("   OTP request successful")
        print(f"Response: {response.json()}")
    else:
        print("  OTP request failed")
        print(f"Error: {response.text}")

def test_student_password_change():
    print("\nTesting Student Password Change...")
    
    # First get a student email (we know there are 2 students from populate)
    # Let's try with the first student
    test_email = "leminh01@gmail.com"  # This should be generated by populate script
    
    response = requests.post(f"{base_url}/student/change-password", 
                           json={
                               "current_password": "123456",  # Default password
                               "new_password": "NewPass123!"
                           },
                           params={"student_email": test_email})
    
    print(f"Student Password Change Status: {response.status_code}")
    if response.status_code == 200:
        print("   Student password change successful")
        print(f"Response: {response.json()}")
    else:
        print("  Student password change failed")
        print(f"Error: {response.text}")

def test_student_login():
    print("\nTesting Student Login with old password...")
    
    response = requests.post(f"{base_url}/auth/login", 
                           json={
                               "email": "leminh01@gmail.com",
                               "password": "123456"
                           })
    
    print(f"Login Status: {response.status_code}")
    if response.status_code == 200:
        print("   Login successful with old password")
        print(f"Response: {response.json()}")
    else:
        print("  Login failed")
        print(f"Error: {response.text}")

if __name__ == "__main__":
    test_admin_password_reset()
    test_student_password_change()
    test_student_login()